### ISSUE TITLE
Add README and link to slides

### ISSUE THREAD

**Issue by mratsim** [kaushalmodi/nim-systemverilog-dpic#3]
I want to showcase that repo ;)

Slides link: https://www.slideshare.net/KaushalModi4/nim-and-dpic-and-systemverilog

**Comment by kaushalmodi** [comment]
> I want to showcase that repo ;)

Wow! Where? :)

I thought I was the only one looking at this repo. So I didn't care adding a README (But I should! .. regardless). So thanks for this ping.
